# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55fdfbb23ec163bf58c5bbb7a415f558176204cdca15c5584705d49e973d71962f16a803caa75218b8467c62d932f17a9b5d82bd4fef5344955205a63222bf81

test:
  secret_key_base: ecae85746000c88c9bd8aeed5814d7a68f21736390873327fdd662b3b2d1096fb793dde8777825a6ac591cd5868088bf2dc90573a026083a656edd8174b807fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
